//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.20107.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.ComponentModel.Composition.Caching {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Internal.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; cannot be an empty string (&quot;&quot;)..
        /// </summary>
        internal static string ArgumentException_EmptyString {
            get {
                return ResourceManager.GetString("ArgumentException_EmptyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value of argument &apos;{0}&apos; ({1}) is invalid for Enum type &apos;{2}&apos;..
        /// </summary>
        internal static string ArgumentOutOfRange_InvalidEnum {
            get {
                return ResourceManager.GetString("ArgumentOutOfRange_InvalidEnum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information about the assembly &apos;{0}&apos; because it has been loaded from the network or the byte stream. Only assemblies loaded from files on disk are supported..
        /// </summary>
        internal static string AssemblyInformationCannotBeCached {
            get {
                return ResourceManager.GetString("AssemblyInformationCannotBeCached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The catalog &apos;{0}&apos; cannot be cached because it doesn&apos;t have a public constructor that accepts &apos;{1}&apos;  as an argument..
        /// </summary>
        internal static string CacheableCatalogMustHaveProperConstructor {
            get {
                return ResourceManager.GetString("CacheableCatalogMustHaveProperConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Empty&gt;.
        /// </summary>
        internal static string CachedTypeCatalog_Empty {
            get {
                return ResourceManager.GetString("CachedTypeCatalog_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid cache : field &apos;{1}&apos; on type &apos;{0}&apos; is not found..
        /// </summary>
        internal static string CachingFieldNotFound {
            get {
                return ResourceManager.GetString("CachingFieldNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid cache : method &apos;{1}&apos; on type &apos;{0}&apos; is not found..
        /// </summary>
        internal static string CachingMethodNotFound {
            get {
                return ResourceManager.GetString("CachingMethodNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following errors occurred :..
        /// </summary>
        internal static string CachingResult_ExceptionMessageHeader {
            get {
                return ResourceManager.GetString("CachingResult_ExceptionMessageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid cache : type &apos;{0}&apos; is not found..
        /// </summary>
        internal static string CachingTypeNotFound {
            get {
                return ResourceManager.GetString("CachingTypeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The catalog cannot be cached as at least one of the contained catalogs does not support caching : &apos;{0}&apos;..
        /// </summary>
        internal static string CatalogIsNotCacheable {
            get {
                return ResourceManager.GetString("CatalogIsNotCacheable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal error occurred. Additional information: &apos;{0}&apos;..
        /// </summary>
        internal static string InternalExceptionMessage {
            get {
                return ResourceManager.GetString("InternalExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid cache token : &apos;{0}&apos;.
        /// </summary>
        internal static string InvalidCacheToken {
            get {
                return ResourceManager.GetString("InvalidCacheToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objects of type &apos;{0}&apos; cannot be written into the cache..
        /// </summary>
        internal static string UnsupportedCacheValue {
            get {
                return ResourceManager.GetString("UnsupportedCacheValue", resourceCulture);
            }
        }
    }
}
